-- Create scouting_data table
create table if not exists scouting_data (
  id bigint generated by default as identity primary key,
  team_number integer not null,
  competition_key text not null,
  shooter_type text,
  hopper_capacity integer,
  autos text,
  feeding boolean not null default false,
  climb text,
  trench boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (team_number, competition_key)
);

-- Enable RLS
alter table scouting_data enable row level security;
create policy "Public read access" on scouting_data for select using (true);
create policy "Public insert access" on scouting_data for insert with check (true);
create policy "Public update access" on scouting_data for update using (true);
