-- Create model_weights table to store the global model's state daily
create table if not exists model_weights (
  id bigint generated by default as identity primary key,
  created_date date not null,
  model_type text not null, -- e.g., 'lasso_global'
  variable_name text not null,
  weight float8 not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (created_date, model_type, variable_name)
);

-- Enable RLS
alter table model_weights enable row level security;

-- Public read access so the frontend can pull the latest weights
create policy "Public read access" on model_weights for select using (true);

-- Service role write access for the daily_job.py script
create policy "Service role write access" on model_weights for all using (true);
